JetBrains/ring-ui

- docs/breaking-changes.md
great job and maybe it's comes from the future  :)
> release date tweaks

- components/global/global.css
- components/global/global.scss
this feature will support in next generation css, ref: https://drafts.csswg.org/css-fonts-4/#system-ui-def
> Add better solution for cross-platform font renderings

- components/date-picker/date-picker.js
I need to show DatePicker initially opened. Adding dropdownProps property and passing it to underlying Dropdown component could be a solution.
> Added ability to pass dropdownProps to DatePicker

- components/input/input.js
Check if Clearable field is disabled. In this case remove 'Close button'
> Clearable-input fix

- components/caret/caret.js
- components/query-assist/query-assist.js
fix - RG-2015 Jumping cursor in query assist
> fix - RG-2015 Jumping cursor in query assist

- components/global/composeRefs.js
- components/global/focus-sensor-hoc.js
- components/table/draggable-row.js
- components/table/row.js
- components/table/table.js
- package.json
- yarn.lock
https://jetbrains.slack.com/archives/G30EZSLBW/p1588095247002000
> Migrate Table to react-movable

- package-lock.json
- package.json
Reverts JetBrains/ring-ui#3111
> Revert "chore(deps): bump imports-loader from 1.2.0 to 2.0.0"

- src/pager/pager.tsx
a page changed to the last one when the current page number is bigger than the number of pages
> fix(pager): the last page problem [RG-2200]

- README.md
The project has been dead for a while https://github.com/alanshaw/david/issues/182.
> Get rid of obsolete David badges

- package-lock.json
- package.json
This is a follow up to https://github.com/JetBrains/ring-ui/pull/5397.
> Get rid of Yeoman

- src/select/select.tsx
- src/tags-input/tags-input.tsx
Also added 'id' customization to TagsInput
> feat: focus implementation added to Select and TagsInput components

- src/date-picker/consts.ts
- src/date-picker/date-input.tsx
- src/date-picker/date-picker.tsx
- src/date-picker/date-popup.tsx
The `hidden` prop will now always be `false`, so I deleted it.
> RG-2315 Do not keep DatePicker popup mounted

- .storybook/main.js
> Make Welcome stories default

- src/editable-heading/editable-heading.css
This is the follow up to https://github.com/jetbrains/ring-ui/commit/5f95d5c365ec986d8536807a9eb722d2e221b1ac.
> RG-2267 fix Level 3 in EditableHeading editing mode

- src/date-picker/date-picker.stories.tsx
Fixes https://teamcity.jetbrains.com/buildConfiguration/JetBrainsUi_RingUi_AllChecks/4546094?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A4546093%29%2Cid%3A2000000057.
> Fix DatePicker console error tests

- src/button/button.stories.tsx
- src/input/input.stories.tsx
- src/radio/radio.stories.tsx
https://youtrack.jetbrains.com/issue/RG-2415/Fix-Broken-Storybook-Pages
> RG-2415 Fix Broken Storybook Pages

- src/popup/popup.tsx
@Hypnosphi JFYI the previous behavior caused the problems with the client-side navigation on YouTrack, e.g. JT-81062.
> RG-2430 Propagate client-side navigation anchor clicks from Popup

- src/popup/popup.tsx
This is the follow-up to https://github.com/JetBrains/ring-ui/pull/7268.
🤦
> RG-2430 Fix isPossibleClientSideNavigation condition

- src/tab-trap/tab-trap.tsx
This is needed to fix a bug where calling the `focus` method programmatically in `componentWillUnmount` does not trigger the React event handler for the `focus` event on the DOM element that the method is called on. It is very similar to this bug https://github.com/facebook/react/issues/17894.
You can see this bug live here: https://codesandbox.io/p/sandbox/new-snow-2zjrsk.
Steps to reproduce:
1. Click the ‘Click me’ button.
2. Two `focus` records will appear in the log - this is normal.
3. Press Escape to close the Date Picker.
4. Another `focus` record should appear in the log, but it does not because the `onFocus` event handler for the button was not called.
> Convert TabTrap to function component to fix the bug with onFocus

- src/table/simple-table.stories.tsx
- src/table/simple-table.tsx
- src/table/table.css
- src/table/table.tsx
https://youtrack.jetbrains.com/issue/RG-2457
> feat(simple-table): add simple table component

- src/tooltip/tooltip.tsx
See [RG-2490](https://youtrack.jetbrains.com/issue/RG-2490) for details
> RG-2490 support moving cursor from anchor to tooltip

- src/table/header.tsx
- src/table/row.tsx
- src/table/table.stories.tsx
- src/table/table.tsx
This API has been added, but is not used anywhere.
> Get rid of unused Table maxColSpan prop

- src/global/variables.css
- src/markdown/markdown.css
- src/table/table.css
[RG-2510](https://youtrack.jetbrains.com/issue/RG-2510) Add 'Regular Tabular' font style
this adds a `--ring-font-variant-numeric` custom property and applies it to the Table component
> RG-2510 Add 'Regular Tabular' font style

- src/table/table.tsx
Backport of https://github.com/JetBrains/ring-ui/pull/8244
> RG-2568 feat(table): accept custom loader

- package-lock.json
- package.json
- prepare-built-package.js
- src/auth/response-parser.ts
- src/auth/token-validator.ts
- src/http/http.ts
> chore: drop "es6-error" package as in current environment there is no need to shim anymore

- package-lock.json
- package.json
https://github.com/JetBrains/postcss-require-hover/pull/1
> RG-2442 update postcss-require-hover

- src/island/adaptive-island-hoc.tsx
https://github.com/user-attachments/assets/2077a2c8-2fe8-4eec-b3ee-9e378d6229e0
> RG-2390 Dialog modal header size scale in Safari

- src/alert-service/alert-service.test.ts
- src/alert-service/alert-service.tsx
This PR changes default timeout from 0 to 10 seconds for `AlertService` component.
> refactor(alertService): set DEFAULT_ALERT_TIMEOUT
