JetBrains/ring-ui

packages/ring-ui-gemini/.gemini.conf.js
It turned out that Sauce Labs provides Firefox 47.0 (Windows 10). Fortunately, there are no image diffs between 42 and 47.
Gemini does not support Firefox 48+ because `gemini` uses `wd` (https://github.com/admc/wd) package which does not support Selenium 3.0 yet. No estimates from gemini side.
=> Update firefox to 47.0 in gemini config

components/auth-dialog-service/auth-dialog-service.examples.js
Currently if you select auth service in storybook and then switch to another section, the auth dialog will remain.
Fixed this by calling remove callback in unmount hook.
=> storybook: fix auth dialog dissapearing after swithcing to another section

CHANGELOG.md, components/old-browsers-message/old-browsers-message.examples.js, webpack.config.js
Applying it as default breaks SASS imports because webpack thinks it can be tree-shaked
=> Only apply "sideEffects: false" to `babel-loader`;

components/loader/loader.js, components/loader/loader__core.js
It's often an issue to test components that use random values. To simplify this, I've added the `deterministic` property to the `Loader` component. It tells the core class to use the function returning a constant instead of `Math.random`.
=> Loader: add `deterministic` prop to be able to derandomize it

components/date-picker/date-picker.css
When viewed in Safari, DatePicker component shows a calendar having 6 days in a week. That's because days are buttons and Safari buttons have extra margin by default. This can be solved by explicitly setting `margin: 0;`
=> 6 days in a week (Safari)

components/popup/popup.js
The solution is to revert the click handlers' order by subscribing to the capture phase.
=> the select should not close the parent popup on value change

components/date-picker/date-picker.test.js, components/date-picker/date-popup.js
Sometimes it is necessary to involve specific components into the date popup. For example, buttons with relative periods (or dates) such as Today, Yesterday, Last Month, etc. We should not foresee all possible scenarios and visual interpretations, but at least we ought to give the possibility of displaying them.
I solve the issue using render props
=> A render prop was introduced for date-popup component

components/date-picker/date-picker.css
Made some selectors for `DatePicker` component more specific, now it looks like in stable version. 
However, it doesn't fix the problem of broken order of selectors in `style.css` bundle, which appears because of using css modules and the way loader processes them. Maybe some other components could be affected.
=> RG-2161: fixed datepicker broken styles

src/global/variables.css, src/global/variables_dark.css, src/table/table.css
This issue is related to the ones from the YouTrack ([Link](https://youtrack.jetbrains.com/issue/RG-2192/Dark-theme-remove-white-background-in-the-table-loader))
Before:
Table loading overlay had a hardcoded background color.
Now:
This overlay has a color which depends on the content color. This changes nothing when it comes to the Light theme. But now in the dark theme it has a proper dark color instead of a hardcoded white color.
=> Support dark overlay background for the table

CONTRIBUTING.md
The generators themselves were removed some time ago.
=> Remove obsolete reference to the use of component generators

src/auth/auth__core.ts, src/header/profile.tsx, src/i18n/README.md, src/i18n/i18n-context.ts, src/i18n/i18n-context.tsx, src/i18n/i18n.examples.tsx, src/i18n/i18n.test.ts, src/i18n/i18n.ts, src/input/input.tsx, src/message/message.tsx, src/pager/pager.test.tsx, src/pager/pager.tsx, src/query-assist/query-assist.tsx, src/select/select.tsx, src/select/select__filter.tsx, src/user-agreement/user-agreement.tsx, src/user-card/card.tsx, src/user-card/user-card.test.tsx
On our weekly meeting, we've agreed to:
1. Change usages of `message.smth` to some function `getMessage('smth')`, because that adds more centralised control
2. In that `getMessage` function, check if we have that key overriden. If not, print warning
2. On type level, have regular "Optional" type `Messages`, so you can skip some messages, and a dedicated `MessagesStrict` so you can opt-in for strict translations typing
3. Add a dedicated Readme for i18n layer
=> RG-2276 update API of translation layer to meet requirements

src/query-assist/query-assist.tsx
Here is some context
https://youtrack.jetbrains.com/issue/JT-70973/Recent-commands-and-suggestions-are-not-shown-when-opening-a-command-window
Here is some proof
https://github.com/JetBrains/ring-ui/assets/10141840/66236503-6bf4-42bc-b8f3-0df8089db068
=> Sometimes dropdown doesn't open

src/editable-heading/editable-heading.tsx
The problem is in this line of code https://github.com/JetBrains/ring-ui/commit/c93f27c12e49b9ae04fdf9e3d3be01315962af06#diff-5f458fe6db99478c84492a8116000facdf632ac46a84e0b3620208761f6a1837R53. The `onChange` handler is no longer passed to the `<input>` as part of `restProps` https://github.com/JetBrains/ring-ui/commit/c93f27c12e49b9ae04fdf9e3d3be01315962af06#diff-5f458fe6db99478c84492a8116000facdf632ac46a84e0b3620208761f6a1837R214.
=> Fix non-multiline EditableHeading

src/table/table.stories.tsx
Named JSON imports are deprecated:
1. https://github.com/webpack/webpack/issues/9246
2. https://github.com/webpack/webpack/pull/9259
3. https://github.com/webpack/webpack.js.org/pull/3141/files#diff-2cfa9614f956cffe79f0110043cb376248298001434e6b267350ba7674e9b0f7R475
=> Do not use named JSON imports in Table stories

src/error-message/error-message.tsx
It was in the Angular.js component https://github.com/JetBrains/ring-ui/blob/ab8314371d0291adbfa984ad8095b2e64d475d42/src/error-message-ng/error-message-ng.js#L24
=> Add ring-error-message-title data attribute

src/date-picker/date-picker.stories.tsx
=> Fix inline DatePicker story

src/date-picker/date-picker.tsx
It is used in this way https://github.com/JetBrains/ring-ui/blob/6b7e85253d5c17e326512ea8ecc1eccd9b811371/src/date-picker/date-picker.tsx#L330 so it makes sense to make it partial.
=> Make DatePicker dropdownProps prop partial type

src/http/http.mock.ts, src/http/http.test.ts, src/http/http.ts
`fetch` cannot return `Partial<Response>` in runtime.
=> Get rid of Partial<Response> in HTTP

src/input/input.tsx
It was removed here https://github.com/JetBrains/ring-ui/commit/a45730a8db247a50406f09627c7e6489fe055a7f#diff-9571a6a46f39072419647c7b25d8afcfee0c28f631246b5e8e2bebdb974db8c4L165.
=> Remove Input .noLabel CSS class usage

src/checkbox/checkbox.tsx, src/global/focus-sensor-hoc.tsx, src/global/rerender-hoc.tsx, src/select/select.tsx, src/select/select__popup.tsx, src/table/row.tsx
This is the follow-up to https://github.com/JetBrains/ring-ui/pull/7458. I am doing the same for all components.
=> Use stable composed ref in all components

src/global/composeRefs.ts
This is the follow-up to https://github.com/JetBrains/ring-ui/pull/7475#discussion_r1659095865.
=> Deprecate composeRefs export

src/date-picker/date-input.tsx, src/tab-trap/tab-trap.tsx
This is the follow-up to https://github.com/JetBrains/ring-ui/pull/7491.
The previous solution with `setTimeout` led to another problem: because focus is not restored immediately, `TabTrap` can steal focus from another component (see video). So I removed `setTimeout` and tried to solve the problem with Enter in `DatePicker` itself. 
https://github.com/JetBrains/ring-ui/assets/153412/8f2aeaaf-3473-4609-80e4-1c2caa40e6fa
=> RG-2450 Date Picker remains open after pressing Enter (another solution)

package-lock.json, packages/screenshots/package.json, packages/screenshots/screenshots.js
`port-claim` doesn't have the following drawbacks:
1. https://github.com/tiaanduplessis/kill-port/issues/61 (<1 second vs. 16 seconds)
2. https://github.com/tiaanduplessis/kill-port/issues/77 (if the port is free, there will be no useless output to the console):
```
Error: No process running on port
at /Users/veniamin.krol/Projects/JetBrains/ring-ui/node_modules/kill-port/index.js:40:49
```
=> Replace kill-port with port-claim

src/toggle/toggle.css
Previously, the root element of the Toggle component was inline (because the default value of the `display` property of the `<label>` HTML element is `inline`). [Here](https://github.com/JetBrains/ring-ui/commit/f9ef698d7cd8e544ed1c220e4c5e57692e1eaa2b#diff-7219d926853aafb9e6afd73c588cbd06fd42c041aa7ab7f770e916ee3629419fR8) `display: flex` has been applied to this label, and it is actually a breaking change because then the `<label>` element has become block.
This change will fix at least 4 broken layout bugs on YouTrack https://youtrack.jetbrains.com/issue/JT-82959.
=> Make Toggle root element inline

src/select/select.tsx
The `setState` updater function should be pure:
1. [https://react.dev/reference/react/useState#setstate-caveats:~:text=In Strict Mode%2C React will call your updater function twice](https://react.dev/reference/react/useState#setstate-caveats:~:text=In%20Strict%20Mode%2C%20React%20will%20call%20your%20updater%20function%20twice)
2. https://react.dev/reference/react/useState#my-initializer-or-updater-function-runs-twice
In Strict Mode it is called twice in the development mode.
Side effects:
1. https://github.com/JetBrains/ring-ui/blob/c1353fd060e51092921f8607024851f8ca5c31c2/src/select/select.tsx#L980
2. https://github.com/JetBrains/ring-ui/blob/c1353fd060e51092921f8607024851f8ca5c31c2/src/select/select.tsx#L983
4. https://github.com/JetBrains/ring-ui/blob/c1353fd060e51092921f8607024851f8ca …
=> RG-2293 Get rid of side effects in setState updater function of Select

src/shortcuts/core.ts
by having '.ring-js-shortcuts' on parent, removed in 473d55402947cfa2d98bcc2fe3a255c9f3f3ee29
=> JT-83359 Enable back controlling shortcuts 

.git-blame-ignore-revs, package.json
Small utility change: within the codebase there might be commits that one wants to ignore for `blame` such as recent `apply prettier suggestions`. See before 
and after
=> chore(git): add .git-blame-ignore-revs

src/data-list/data-list.test.tsx, src/table/row.tsx, src/table/selection.ts, src/table/simple-table.stories.tsx, src/table/table.stories.tsx
For example, this is what we have to do to extend `SelectionItem` without this fix:
```ts
export interface CustomAppInTableSelection extends CustomAppLite {
// hack for TableSelection type mismatching
[k: string]: unknown;
}
...
selection: TableSelection<CustomAppInTableSelection>;
```
=> Drop index type from SelectionItem to make the typings more strict

src/alert/alert.css, src/button-group/button-group.css, src/button/button.css, src/checkbox/checkbox.css, src/content-layout/content-layout.css, src/data-list/data-list.css, src/date-picker/date-picker.css, src/global/global.css, src/grid/grid.css, src/header/header.css, src/island/island.css, src/loader-inline/loader-inline.css, src/markdown/markdown.css, src/progress-bar/progress-bar.css, src/query-assist/query-assist.css, src/select/select.css, src/slider/slider.css, src/table/table.css, src/tabs/tabs.css, src/tag/tag.css, src/toggle/toggle.css
I think it makes sense to reduce usage of non-standard CSS syntax to bare minimum
Therefore I replaced local usages of `@value` syntax with CSS Custom Properties
`@value` is still used to import hashed classNames from other CSS files, but this is covered by `postcss-modules-values` [plugin](https://github.com/madyankin/postcss-modules/blob/bd64c71ddfd81b615104b0727ce9a623da0eaef6/src/scoping.js#L6) and is a part of CSS Modules stack
=> Reduce usage of postcss-modules-values-replace `@value` syntax for future plugin removal

eslint.config.mjs, tsconfig.json
`@jetbrains-eslint/base` config [brings](https://github.com/JetBrains/eslint-config/blob/2536514f81ee4bef52640edd13f1b7697b3b737b/base.js#L36) `consistent-returns` rule which is not convenient in scope of React + TS. We can leverage return consistency on `tsconfig` as proposed in this PR and plus it helps avoiding unnecessary branching as shown [here](https://github.com/JetBrains/ring-ui/blob/0c3031128e75ad7a7d122194991bf42906d58553/src/collapse/collapse-content.tsx#L55-L61)
=> chore(eslint): rely on tsconfig on functions returns

src/button-group/button-group.css
This prevents selected buttons from appearing above items with --ring-fixed-z-index
=> create an isolated z-index context for button-group

src/query-assist/query-assist.tsx
Before:
https://github.com/user-attachments/assets/8f6dae09-de5b-4676-9b3e-9763d9da271e
After:
https://github.com/user-attachments/assets/77ee93f4-3747-4b67-9076-d6841873d652
=> Remove QuickAssist placeholder from tab order

packages/screenshots/testplane/chrome/components/collapse/expanded by default/expanded by default-dark.png, packages/screenshots/testplane/chrome/components/collapse/with controlled collapse state/with controlled collapse state-dark.png, packages/screenshots/testplane/firefox/components/collapse/expanded by default/expanded by default-dark.png, packages/screenshots/testplane/firefox/components/collapse/with controlled collapse state/with controlled collapse state-dark.png, src/collapse/collapse-content.tsx, src/collapse/collapse.stories.tsx, src/collapse/collapse.test.tsx, src/collapse/collapse.tsx
One of the users requested to stop rendering the content after the collapsed component was collapsed.
Since the Collapse component has animation, I am using the `transitionend` event to track whenever the content is hidden, which helps to understand when the content can be hidden.
| Attribute | Type                         | Description                                                                      | Default |
|-----------|------------------------------|----------------------------------------------------------------------------------|---------|
| defaultCollapsed  | boolean                    | This prop controls whether the collapse component should be expanded by default.              | false       |
| collapsed  | boolean \| null                    | This prop controls the …
=> <Collapse /> component: Stop rendering the collapsed content.

packages/screenshots/testplane/chrome/components/dropdownmenu/dropdownmenu with custom children/dropdownmenu with custom children-dark.png, packages/screenshots/testplane/chrome/components/dropdownmenu/dropdownmenu with custom children/dropdownmenu with custom children-dropdown.png, packages/screenshots/testplane/firefox/components/dropdownmenu/dropdownmenu with custom children/dropdownmenu with custom children-dark.png, packages/screenshots/testplane/firefox/components/dropdownmenu/dropdownmenu with custom children/dropdownmenu with custom children-dropdown.png, src/dropdown-menu/dropdown-menu.stories.tsx, src/dropdown-menu/dropdown-menu.tsx, src/dropdown/dropdown.tsx, src/header/profile.tsx
So it makes it possible to access `popupProps` and call methods from it, e.g. `onCloseAttempt`.
Case: when one renders `DropdownMenu` inside of a `DropdownMenu` and wants to close the parent `DropdownMenu` on the children's select. Otherwise consumer have to stop event propagation on the wrapper level, and create hackish solutions such as `DropdownMenu` key re-generation on `onSelect` calls.  Example in story.
=> RG-2525 feat(DropdownMenu): accept children

src/list/list.css
`.error` className seems to be unused, so I removed it. Please check that I haven't accidentally missed it
=> RG-2556 fix(List): remove hover styles when custom item is disabled

packages/screenshots/testplane/chrome/style-only/old browsers message/old browsers message/old browsers message-dark.png, packages/screenshots/testplane/chrome/style-only/old browsers message/old browsers message/old browsers message.png, src/old-browsers-message/old-browsers-message.css
This PR replaces outdated fallback font families for MacOS with the 'modern' one.
=> chore: replace outdated generic system mac font families

src/list/list.tsx
`nextProps !== this.props` is always `true` in React 19, so `setState` in `componentDidUpdate` results in an infinite loop. I also use `Object.is` because the `maxHeight` prop can contain `NaN`, `NaN` !== `NaN`.
=> Fix List shouldComponentUpdate

package.json
Without this change, you would have to specify extensions for Ring UI imports if you're using ESM (type module or .mjs)
```
ERROR in ./node_modules/@jetbrains/teamcity-ui/dist/Markdown-D1tTSe7K.mjs 3:0-76
Module not found: Error: Can't resolve '@jetbrains/ring-ui-built/components/global/normalize-indent' in '/Users/filippriabchun/WebstormProjects/teamcity-react-plugins/teamcity-cloud-plugins/hosted-plugin-server/frontend/node_modules/@jetbrains/teamcity-ui/dist'
Did you mean 'normalize-indent.js'?
BREAKING CHANGE: The request '@jetbrains/ring-ui-built/components/global/normalize-indent' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where …
```
=> Add "exports" field to better support native ESM environments

packages/screenshots/testplane/chrome/components/select/multiple with a description/multiple with a description-selectwithpopup.png, packages/screenshots/testplane/firefox/components/select/multiple with a description/multiple with a description-selectwithpopup.png, src/select/select.stories.tsx, src/select/select.tsx
The problem occurred because activeIndex (highlighted item) was calculated before the reset button and separator were added to the list.
As a result, the highlighted item appears two positions earlier than the actual selected one (see video 1)
https://github.com/user-attachments/assets/0ea98a40-582a-4576-b90a-f0a1b31dd84f
**Current behavior (video 2):**
- Keys are now used instead of indexes to determine which item to highlight — this is safer and more stable 
- Only actual option items (not separators or reset buttons) can be auto-highlighted when the popup opens
- The last selected/unselected element is highlighted after interaction
- In multiselect mode, the last selected tag is highlighted when the popup opens
This behavior now matches the UX of other UI kits such as [Material …
=> RG-2197 fix auto highlight for multi select

src/loader/loader.tsx
Now only canvas and loader text have data-test attributes
=> RG-2587 - remove excess data-test attr in the Loader

src/tooltip/tooltip.test.tsx, src/tooltip/tooltip.tsx
If the `title` prop changes to an empty value after `Tooltip` has been displayed or scheduled to be displayed, the tooltip should be hidden.
https://github.com/user-attachments/assets/12b986da-3902-4401-8fab-8f718a412596
=> Hide Tooltip if title prop changes to null or undefined

src/pager/pager.tsx
If total is less than page size and page selector is disabled, then pager is rendered as an empty div with class names.
=> fix: do not render pager if total is less than page size

src/data-list/item.tsx, src/text/text.tsx
At the moment, the `size` prop of the `Text` component is both optional and doesn't have default value. 
This PR:
1. Sets the default value of the `size` prop to `Text.Sizes.M`
2. Improves type definitions for the `Text` component
=> [RG-2644] Set `<Text>` default size to `M`

src/tooltip/tooltip.test.tsx, src/tooltip/tooltip.tsx
Added `focusin` and `focusout` event handlers to the `<Tooltip>` component to satisfy the keyboard focus management requirements.
=> [RG-2654] Tooltip – handle keyboard focus

src/button-group/button-group.css, src/button/button.css, src/checkbox/checkbox.css, src/date-picker/date-picker.css, src/error-bubble/error-bubble.css, src/global/variables.css, src/header/header.css, src/input-size/input-size.css, src/loader-inline/loader-inline.css, src/progress-bar/progress-bar.css, src/tabs/tabs.css, src/tooltip/tooltip.css
Important note – `:root` doesn't have effect when applied within Shadow DOM.
Please, find the repro project attached below. Just unzip it and follow the instruction in its README file.
[ring-ui-shadow-dom.zip](https://github.com/user-attachments/files/22049771/ring-ui-shadow-dom.zip)
=> [RG-2652] Add `:host` selector to all `:root` styles for shadow-root compatibility

src/select/select.tsx
The function value wasn't evaluated in Select classnames
=> Fix controls height usage in Select
